// <auto-generated />
namespace AgendaDeContatos.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class criaContato : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(criaContato));
        
        string IMigrationMetadata.Id
        {
            get { return "201801311904152_criaContato"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
